# Generated by Django 5.2.4 on 2026-03-19 21:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomePurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pattern', models.TextField(default='NoChance2Match^')),
            ],
        ),
        migrations.CreateModel(
            name='DinoHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nick_name', models.CharField(blank=True, max_length=150, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('date_order', models.IntegerField(choices=[(1, 'Ascending'), (-1, 'Descending')], default=-1)),
                ('preprocess_function_name', models.CharField(default='default', max_length=100)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('date_order__in', [1, -1])), name='date_order_must_be_1_or_minus_1')],
            },
        ),
        migrations.CreateModel(
            name='ExpenditurePurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pattern', models.TextField(default='NoChance2Match^')),
                ('color', models.CharField(default='#000', max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditure_purpose_category', to='dinoapi.expenditurecategory')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceColumnMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(default='iban', max_length=100)),
                ('amount', models.CharField(default='amount', max_length=100)),
                ('balance', models.CharField(default='balance', max_length=100)),
                ('currency', models.CharField(default='currency', max_length=100)),
                ('booking_date', models.CharField(default='booking_date', max_length=100)),
                ('payment_participant_name', models.CharField(default='payment_participant_name', max_length=100)),
                ('intention', models.CharField(default='intention', max_length=100)),
                ('payment_type', models.CharField(default='payment_type', max_length=100)),
                ('account_name', models.CharField(default='account_name', max_length=100)),
                ('bic', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(default='bank_name', max_length=100)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_invoice_column_map', to='dinoapi.bank')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_acc_bank', to='dinoapi.bank')),
                ('user', models.ManyToManyField(related_name='bank_account_user', to=settings.AUTH_USER_MODEL)),
                ('column_map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_acc_invoice_column_map', to='dinoapi.invoicecolumnmap')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('booking_date', models.DateField(default=None, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('payment_type', models.CharField(blank=True, default='', max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_account', to='dinoapi.bankaccount')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100)),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_purpose', to='dinoapi.incomepurpose')),
                ('transaction', models.OneToOneField(limit_choices_to={'amount__gte': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='income_transaction', to='dinoapi.transaction')),
            ],
            options={
                'ordering': ['-transaction__booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditure_purpose', to='dinoapi.expenditurepurpose')),
                ('transaction', models.OneToOneField(limit_choices_to={'amount__lt': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='expenditure_transaction', to='dinoapi.transaction')),
            ],
            options={
                'ordering': ['-transaction__booking_date'],
            },
        ),
    ]
